// Generated by gencpp from file cone_detector/positionFromDetectRGB.msg
// DO NOT EDIT!


#ifndef CONE_DETECTOR_MESSAGE_POSITIONFROMDETECTRGB_H
#define CONE_DETECTOR_MESSAGE_POSITIONFROMDETECTRGB_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cone_detector
{
template <class ContainerAllocator>
struct positionFromDetectRGB_
{
  typedef positionFromDetectRGB_<ContainerAllocator> Type;

  positionFromDetectRGB_()
    : who(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , flag(0)  {
    }
  positionFromDetectRGB_(const ContainerAllocator& _alloc)
    : who(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , flag(0)  {
    }



   typedef int8_t _who_type;
  _who_type who;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef int16_t _flag_type;
  _flag_type flag;




  typedef boost::shared_ptr< ::cone_detector::positionFromDetectRGB_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cone_detector::positionFromDetectRGB_<ContainerAllocator> const> ConstPtr;

}; // struct positionFromDetectRGB_

typedef ::cone_detector::positionFromDetectRGB_<std::allocator<void> > positionFromDetectRGB;

typedef boost::shared_ptr< ::cone_detector::positionFromDetectRGB > positionFromDetectRGBPtr;
typedef boost::shared_ptr< ::cone_detector::positionFromDetectRGB const> positionFromDetectRGBConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cone_detector::positionFromDetectRGB_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cone_detector::positionFromDetectRGB_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cone_detector

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'cone_detector': ['/home/scuak/rmv4/src/cone_detector/msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cone_detector::positionFromDetectRGB_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cone_detector::positionFromDetectRGB_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cone_detector::positionFromDetectRGB_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cone_detector::positionFromDetectRGB_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cone_detector::positionFromDetectRGB_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cone_detector::positionFromDetectRGB_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cone_detector::positionFromDetectRGB_<ContainerAllocator> >
{
  static const char* value()
  {
    return "876ca217fcc53faec876347db09a50ba";
  }

  static const char* value(const ::cone_detector::positionFromDetectRGB_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x876ca217fcc53faeULL;
  static const uint64_t static_value2 = 0xc876347db09a50baULL;
};

template<class ContainerAllocator>
struct DataType< ::cone_detector::positionFromDetectRGB_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cone_detector/positionFromDetectRGB";
  }

  static const char* value(const ::cone_detector::positionFromDetectRGB_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cone_detector::positionFromDetectRGB_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 who\n\
float32 x\n\
float32 y\n\
float32 z\n\
int16 flag\n\
";
  }

  static const char* value(const ::cone_detector::positionFromDetectRGB_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cone_detector::positionFromDetectRGB_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.who);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct positionFromDetectRGB_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cone_detector::positionFromDetectRGB_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cone_detector::positionFromDetectRGB_<ContainerAllocator>& v)
  {
    s << indent << "who: ";
    Printer<int8_t>::stream(s, indent + "  ", v.who);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "flag: ";
    Printer<int16_t>::stream(s, indent + "  ", v.flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONE_DETECTOR_MESSAGE_POSITIONFROMDETECTRGB_H
